/// Flutter icons TravelokaIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TravelokaIcons
///      fonts:
///       - asset: fonts/TravelokaIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TravelokaIcons {
  TravelokaIcons._();

  static const _kFontFam = 'TravelokaIcons';
  static const String? _kFontPkg = null;

  static const IconData spikeyball = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baggage = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
